charts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from charts import views

app_name = 'chartapp'

urlpatterns = [
    url(r'^chart/$', views.chartView, name='chart'),
]

fUpload/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from fUpload import views

app_name = 'fUploadapp'

urlpatterns = [
    url(r'^fupload/$', views.fUpload, name='file_upload'),
    url(r'^lista_fajlova/', views.FajloviListView.as_view(), name='lista_fajlova'),
]

pycharm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from blogapp import views
from kalkulator import views
from fUpload import views

urlpatterns = [
    url(r'^admin/', admin.site.urls, kwargs='',name='admin'),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^home/$', TemplateView.as_view(template_name='index.html'), name='pocetna'),
    url(r'^blog/', include('blogapp.urls', namespace='blogapp')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^kalkulator/', include('kalkulator.urls', namespace='kalkulatorapp')),
    url(r'^charts/', include('charts.urls', namespace='chartapp')),
    url(r'^fupload/', include('fUpload.urls', namespace='fUploadapp')),
]

fUpload/models.py
from django.db import models
# Create your models here.

class DataModel(models.Model):
	naziv = models.CharField(max_length = 50)
	datoteka = models.FileField(upload_to='documents/%Y/%m/%d')

	def __str__(self):
		return self.naziv

fUpload/forms.py
from django import forms
from django.forms import ModelForm
from .models import DataModel

# Create the form class.
class ProfileForm(ModelForm):
	class Meta:
		model = DataModel
		fields = ('naziv', 'datoteka')

fUpload/views.py
from django.shortcuts import render
from fUpload.forms import ProfileForm
from fUpload.models import DataModel
from django.http import HttpResponseRedirect
from django.contrib import messages 
# Create your views here.

def fUpload(request):
	form = ProfileForm(request.POST, request.FILES)
	file_uploaded = False
	if request.method == 'POST':
		print("POST metod")
		
		print(form)

		if form.is_valid():
			# print('forma validna /fUpload.views.fUpload')
			# form.save()
			# print("Snimljeno")
			file_name, file_size, read_file = manipulacija_file(request.FILES['datoteka'])

			instance = DataModel(datoteka=request.FILES['datoteka'])
			#print(DataModel.datoteka.name)
			#instance.save()
			form.save()
			file_uploaded = True
			
			print("Iz form valid")
			print(read_file)
			return render(request, 'fUpload/fUpload.html', {'form': form,
															'file_name': file_name,
															'file_size': file_size,
															'file_uploaded': file_uploaded,
															'read_file': read_file})

		else:
			print('Forma nije validna')
			a=form.errors
			print(a)
			messages.error(request, "Error")
			
			form = ProfileForm()

	return render(request, 'fUpload/fUpload.html', {'form': form, 'file_uploaded': file_uploaded})


#FUNKCIJA ZA MANIPULACIJU FAJLOM
def manipulacija_file(f):
	file_name = f.name
	file_size = f.size
	read_file = f.read()
	print(read_file)
	read_file=brisanje_zareza(read_file)

	print(read_file)
	return file_name, file_size, read_file



def brisanje_zareza(linija):
	dekodovano=str(linija, 'utf-8')
	#splitovano=linija.split(b' ')
	dekodovano=dekodovano.replace('.','ALEKSA')
	return dekodovano




from django.views.generic.list import ListView


class FajloviListView(ListView):
	model = DataModel
	template_name = 'fUpload/lista_fajlova.html'
	context_object_name = 'lista_fajlova'

fUpload/templates/fUpload/fUpload.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap %}


{% block content%}

<div class="container">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}		
			{{form|bootstrap}}
			<input class="btn btn-warning" type="submit" name="Upload">
	</form>
	{% if file_uploaded%}
		<h5>File: <em>{{file_name}}</em> with size of: <em>{{file_size}}KB</em> is uploaded. Thank you.</h5>
	{%endif%}


		<h1><a href="{% url 'fUploadapp:lista_fajlova' %}">Link ka lisit</a></h1>
	<br><br><br><br>

	<div class="panel panel-success">
      <div class="panel-heading">Content of the uploaded file:</div>
      <div class="panel-body">{{read_file|safe}}</div>
    </div>



</div>



{% endblock%}

fUpload/templates/fUpload/lista_fajlova.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap %}


{% block content%}

<div class="container">

<h1>Lista svih uploadovanih fajlova:</h1>
<br><br>
  <table class="table">
    <thead>
      <tr>
        <th>Naziv</th>
        <th>Lastname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
    {% for i in lista_fajlova%}
      <tr>
        <td>{{i.naziv}}</td>
        <td>{{i.datoteka}}</td>
        <td><a href="{{i.datoteka}}">link</a>	</td>
      </tr>
     {%endfor%}
    </tbody>
  </table>



</div>



{% endblock%}