accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    url(r'logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'signup/$', views.SignUp.as_view(), name="signup"),
]



blogapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from blogapp import views

app_name = 'blogapp'

urlpatterns = [
    url(r'^new_post/$', views.KreirajPostView.as_view(), name='create_post'),
    url(r'^post_list/$', views.ListaPostovaView.as_view(), name='lista_postova'),
    url(r'^post/(?P<pk>\d+)$', views.DetaljPostaView.as_view(), name='post_pojedinacan'),
    url(r'^about_me/$', views.AboutMeView.as_view(), name='about_me')
]

charts/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from charts import views

app_name = 'chartapp'

urlpatterns = [
    url(r'^chart/$', views.chartView, name='chart'),
]

fUpload/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from fUpload import views

app_name = 'fUploadapp'

urlpatterns = [
    url(r'^fupload/$', views.fUpload, name='file_upload'),
    url(r'^lista_fajlova/', views.FajloviListView.as_view(), name='lista_fajlova'),
]

kalkulator/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from kalkulator import views

app_name = 'kalkulatorapp'

urlpatterns = [
    url(r'^app1/$', views.kalkulator_forma, name='kalkulator'),
    url(r'^rezultat/$', views.rezultat, name='rezultat')
]

pycharm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from blogapp import views
from kalkulator import views
from fUpload import views

urlpatterns = [
    url(r'^admin/', admin.site.urls, kwargs='',name='admin'),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^home/$', TemplateView.as_view(template_name='index.html'), name='pocetna'),
    url(r'^blog/', include('blogapp.urls', namespace='blogapp')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^kalkulator/', include('kalkulator.urls', namespace='kalkulatorapp')),
    url(r'^charts/', include('charts.urls', namespace='chartapp')),
    url(r'^fupload/', include('fUpload.urls', namespace='fUploadapp')),
]

templates/aboutme.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content%}

	<div class="container">
		<p>This is some text about me</p>
		<p>Some random number:</p>
		<h3>{{nasumicni_broj}}</h3>
		<p>Voila!</p>


	</div>


{%endblock%}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap %}
<html>
  <head>
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>One quality blog website</title>
    <link rel="stylesheet" href="{% static "pycharm/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merriweather">
    <link rel="stylesheet" href="{% static 'pycharm/css/styles.css'%}">
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
            <div class="navbar-header"><a class="navbar-brand navbar-link" href="#">My Blog</a>
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
            </div>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav navbar-left">
                    <li role="presentation"><a href="{% url 'pocetna' %}">Home</a></li>

                    <li role="presentation"><a href="{% url 'blogapp:about_me'%}">About Me</a></li>
                    <li role="presentation"><a href="{% url 'admin:index' %}">Admin </a></li>

                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">Aplikacije
                      <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li role="presentation"><a href="{% url 'kalkulatorapp:kalkulator' %}">Kvadratna jednacina</a>
                        <li role="presentation"><a href="{% url 'chartapp:chart' %}">Grafici</a>
                        <li role="presentation"><a href="{% url 'fUploadapp:file_upload' %}">File upload</a>
                      </ul>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">

                  {% if user.is_authenticated %}
					<li role="presentation"><a href="">Dobrodosao: {{user.username}}</a></li>
                    <li role="presentation"><a href="{% url 'blogapp:create_post' %}">New Post</a></li>
					<li role="presentation"><a href="{% url 'blogapp:lista_postova' %}">Post List</a></li>
                    <li role="presentation"><a href="{% url 'accounts:logout' %}">Logout </a></li>
                  {%else%}
                    <li role="presentation"><a href="{% url 'accounts:signup' %}">SignUp </a></li>
                    <li role="presentation"><a href="{% url 'accounts:login' %}">Login </a></li>
                  {%endif%}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}




  </body>

    <script src="{% static 'pycharm/js/jquery.min.js' %}"></script>
    <script src="{% static 'pycharm/bootstrap/js/bootstrap.min.js' %}"></script>
</html>

templates/hvala.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <h1>Hvala </h1>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <img src="{% static 'pycharm/img/pexels-photo.jpeg' %}" alt="">

    <div class="container">

        <h1>Welcome {{user.username}}</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
        cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
        proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	
        <br><br><br>

            <div class="panel-group">
      <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" href="#collapse1">Collapsible panel</a>
              </h4>
            </div>
            
            <div id="collapse1" class="panel-collapse collapse">
                <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
                <div class="panel-footer">Ovo je kraj teksta</div>
            </div>
        </div>
    </div>

    </div>




	
{% endblock %}